server:
  port: 0

# application id
spring:
  application:
    name: "eclient2"

# useless setting for server and services load target
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
