server:
  port: 8765

# application id
spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# useless setting for server and services load target
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
