server:
  port: 8761

# application id
spring:
  application:
    name: "eserver"

# useless setting for server and services load target
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://localhost:8761/eureka"

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF